# Generated by Django 3.2.6 on 2021-08-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionvalue',
            old_name='name',
            new_name='value',
        ),
    ]
