# Generated by Django 3.2.6 on 2021-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_optionvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproduct',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
