# Generated by Django 3.2.6 on 2021-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproduct',
            name='original_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
