# Generated by Django 3.2.6 on 2021-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='donation',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
