# Generated by Django 3.2.6 on 2021-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
        ('order', '0003_auto_20210828_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='target',
        ),
        migrations.AddField(
            model_name='order',
            name='target',
            field=models.ManyToManyField(blank=True, to='product.Quantity'),
        ),
    ]
